# Generated by Django 5.1.5 on 2025-01-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='endereco',
            new_name='mensagem',
        ),
    ]
