# Generated by Django 5.1.5 on 2025-01-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvip', '0002_rename_endereco_socio_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='mensagem',
            new_name='descricao',
        ),
    ]
