# Generated by Django 5.1.5 on 2025-01-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruteira_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruta',
            options={},
        ),
    ]
