# Generated by Django 5.1.5 on 2025-01-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruteira_app', '0002_alter_fruta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruta',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='fruta',
            name='descricao',
        ),
    ]
