# Generated by Django 5.1.5 on 2025-01-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruteira_app', '0003_alter_fruta_options_remove_fruta_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruta',
            options={'ordering': ['nome'], 'verbose_name': 'Fruta', 'verbose_name_plural': 'Frutas'},
        ),
        migrations.AlterField(
            model_name='fruta',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
